#
# Static Configuraiton
#

providers:
  docker: {}

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

log:
  level: "DEBUG"

api:
#  insecure: true
  dashboard: true
  debug: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "candle@jaccard.us"
#      caServer: foobar
      storage: "/etc/traefik/acme.json"
#      keyType: foobar
#      dnsChallenge:
#        provider: foobar
#        delayBeforeCheck: 42
#        resolvers:
#        - foobar
#        - foobar
#        disablePropagationCheck: true
      httpChallenge:
        entryPoint: "web"
#      tlsChallenge: {}
