#
# Static Configuraiton
#

providers:
  docker: {}

entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

log:
  level: "DEBUG"

api:
#  insecure: true
  dashboard: true
  debug: true
