version: '3.3'

networks:
  inside:
    external:
      name: candle-net
  

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - /home/blog/candle/site:/var/www/html
      - /home/blog/candle/conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - inside
#    ports:
#      - 8088:80
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: CFAS2mPxNaVm2qU2YkHH

        # This was for nginx-proxy, but didn't seem to work
        # VIRTUAL_HOST: candle.jaccard.us

    labels:

      # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      # Traefik Labels
      - "traefik.enable=true"

      # HTTP to HTTPS redirect middleware
      - "traefik.http.middlewares.wordpress-http-redirect.redirectScheme.scheme=https"
      - "traefik.http.middlewares.wordpress-http-redirect.redirectScheme.permanent=true"

      # http target
      - "traefik.http.routers.wordpress-http.entrypoints=web"
      - "traefik.http.routers.wordpress-http.rule=Host(`candle.jaccard.us`)"
      - "traefik.http.routers.wordpress-http.middlewares=wordpress-http-redirect"

      # https target
      - "traefik.http.routers.wordpress-https.entrypoints=web-secure"
      - "traefik.http.routers.wordpress-https.rule=Host(`candle.jaccard.us`)"
      - "traefik.http.routers.wordpress-https.tls=true"
      - "traefik.http.routers.wordpress-https.tls.certresolver=letsencrypt"

      # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
      # Filebeat Labels
      # These are used by autodiscover with hints enabled.  I think.
      - "co.elastic.logs/module=apache2" 
      - "co.elastic.logs/fileset.stdout=access" 
      - "co.elastic.logs/fileset.stderr=error" 


  db:
    image: mysql:5.7
    volumes:
      - /home/blog/candle/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2sgved3qGy3w6Gp7BeyM
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CFAS2mPxNaVm2qU2YkHH
    networks:
      - inside
    labels:
      - traefik.enable=false

#  adminer:
#    image: adminer:4.6.3-standalone
#    labels:
#      - traefik.backend=adminer
#      - traefik.frontend.rule=Host:db-admin.jaccard.us
#      - traefik.docker.network=web
#      - traefik.port=8091
#    depends_on:
#      - db
#    networks:
#      - internal
#      - web

